### ISSUE TITLE
GitHub Actions have been failing for 6 months

### ISSUE THREAD

**Issue by cclauss** [pylint-dev/pylint-django#376]
# https://github.com/PyCQA/pylint-django/actions

**WARNING:**  Please do not report issues about missing Django, see
[README](https://github.com/PyCQA/pylint-django#installation)!

**TODO:** make sure to post the output of `pip freeze`

**NOTES:**  make sure you have the latest version of 3rd party packages
like `rest_framework`, `factory`, `model_utils`, etc. before reporting
issues!

**Comment by cclauss** [comment]
9 months...

**Comment by carlio** [comment]
Finally fixed :-)
