### ISSUE TITLE
RecursionError

### ISSUE THREAD

**Issue by duaneking** [pylint-dev/pylint-django#420]
I found this while trying to help with https://github.com/microsoft/vscode-pylint/issues/454 and the output/error can be found there, 

I'm making this ticket as a good faith effort to help issues get fixed, but I'm limited by the fact I'm not working on open source code, so i'm hoping the stack traces and other data there are useful.

**Comment by carlio** [comment]
It looks like from the issue that you linked, the issue you're facing is not supported by pylint
 - 
https://pylint.readthedocs.io/en/latest/faq.html#i-want-to-use-pylint-on-each-keystroke-in-my-ide-how-can-i-do-that
